name: exemplo
channels:
  - conda-forge
dependencies:
  - graph-tool
  - jupyterlab
  - seaborn
  - rise
  - ndlib
  - igraph
  - networkx
  - xorg-libxcursor
  - xorg-libxdamage
  - xorg-libxcomposite
  - xorg-libxrandr
  - xorg-libxinerama
